language: node_js
node_js:
- 6.1.0
install:
- npm install --dev
script:
- npm test
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.fr.cloud.gov
  organization: gsa-acq-proto
  space: trello-card-tracker
  on:
    repo: 18F/trello-card-tracker
