language: node_js
node_js:
- 6.1.0
install:
- npm install --dev
script:
- npm test
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.cloud.gov
  username: 18f-acq_deployer
  secure: "BCZKwUstv+RoL6ChiSdBd7T6LsNEBoSkSGccgjATZ/5Y1fFq4jGKGrVA32q0TqG30D6Hjq1Pdi8qrjRlz1f/iA6bHdYjHCTeXJdkrwLvmpikhPt3gI/jq5w27a676O7N8bdNfaTPiB33aazDK/GfGksS4CfjbAGRgivraAUMPrD2q8lmb6YNgfueqUx0vlixPaH0TqJowO/t0sp1yJQuDpwken0Va8cYPIeuDebeavaXtuP+XoIk66kj5UOf70D7ktZlPtNBuoPVZr6sJYnVS8SQJQotlnYoHR54BH3l+cT3qCopPyw9uL4s2uhnFc2thz7hsOnL3nRGJfmn9nnls9LiM9kw8LtrchbRjcKbpt16tVjopMgpibS2n5X9hxEgZMwqlgMX2QLIp1GRDp1mdJYVxsVArIlWUoZhVhu3R0fSYSzuZFaewgMWDsa14RnEUuzAWsSvA9yoUilHP2NGPAKBtajMG8D95zKnykVgSlc0twDln2mF4MS/+0OM8oq52SVxmT5cMJSj+kfUau9d6MI8N2UPrZjYmV+dcz+CNyiIXEGxLcL2Ol8VOhDc2QKw1qi71sAbXZWC0pQEBKsZGTjWM0a5tIL3cTZ6O3iAst35/SmbRCSuuevudpalrKhzMFPpqjop6YgzBNYdQTKkpEf/N9e0WHUrlhIivGFB2GA="
  organization: 18F-acq
  space: tools
  on:
    repo: 18F/bpa-trello
