language: node_js
node_js:
- 6.1.0
install:
- npm install --dev
script:
- npm test
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.cloud.gov
  username: 18f-acq_deployer
  password:
    secure: Je8/GJwMpnIvaW40rv9ADHkhOyLoGWLGvwp6uHQx1TOEg4lLzE2/anH4/xQ/mX2yUtlwqCEW9TK74XVmiTN74H0yqoIbpXBvST5kTRmlxNqEmq/OERe5PfaFJFYfF+0TmTWSBnhNUSk9OYjVuGhhWHISDmoWAd8P8UMtoO41j2G7fynwIinZktg22+7l9o5pW2kkiAeLt0TAKUHUT0E9IQCUnOtUMe5ZMAIGmVUmhbksQ7gC4l2K6veRpCW3HDsNk0xyHFrEscV1hEmKnogFvg486Cr9SX1+jxa07/mwMRdA1Uwz1jeHBwl0OEyybPa5ONXxQhxm2QldAit7jkmEj6/xNPaUHUkMmGKi9Hr3TY2s1h2T6lF8dLvv6jDDfC0kdoJE4R7VeSGGjmdUtPqQDumwVyjjE6GBhDvelOKqspAkpjwIjCW7UbvmpUanyY6V4rPrzdEELatvz1Ij0dw09iD58qMjVeXBtK/xIZ0eBRiatjtyYul5hyZ1FCTNc2CjmtqrImwqcJ/YMvZ2Dz8mhrG5wnxU8OPLpWSQ8UhbMlb/cEkMTnfzU4fqbGGUYcscxNbeNDspVZersMtCrLhwMsVcnmLQRH4cXG4S543UNEVYzqemfZirXXXtaIAtJ+5SzyGTqaqfrO+6JNMahEWmhX60kgmPJUWux6qBKX+WlQc=
  organization: 18F-acq
  space: tools
  on:
    repo: 18F/bpa-trello
